# 私有源
source 'https://github.com/kaibuleite/xSpecs.git'

use_frameworks!

platform :ios, '9.0'

target 'xManager_Example' do
  pod 'xManager', :path => '../'

  target 'xManager_Tests' do
    inherit! :search_paths

    
  end
end
